# Generated by Django 5.0.6 on 2024-05-21 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0003_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
